### ISSUE TITLE
Yolka repository layout

### ISSUE THREAD

**Issue by ruspl-afed** [arsysop/yolka#2]
We need to invent good repository layout to support multi-language modules development and CI

The languages we are usng most actively are:
* Java
* Rust

The build systems we are using most actively are:
* Maven/Gradle
* Cargo

The repository and module layout should be IDE-friendly

**Comment by eparovyshnaya** [comment]
The following structure for set of _project_ s looks promising: 
 - on top level we define _clusters_: semantical dedication for the embraced tools and libraries
 - a _cluster_ packs _project_ s by  the main _build-system_ of a project
 - each _project_'s layout suits the _build system_
 - a complicated _cluster_ (the one that aggregates _project_ s of different natures under a swath of _build systems_) can also make use of specific facilities that ensure quality of inter-project cooperation. 

Here is the picture

- cluster*
  - build-system*
      - project*
         - [project layout for the build system]
  -  [cluster orchestrating facilities]

For example, for an eclipse subsystem A it would look like this:
 - A/
    - ci-actions/
       - update-documentation.action
    - mvn/
       - bundles/
       - features/
       - releng/
       - pom.xml
    - latex
       - user-guide
          - src
             - user-guide.tex
       - dev-guide
          - src
             - dev-guide.tex
       - .gitignore
